#ifndef CHRONOS_PACKETCONSTANTS_H
#define CHRONOS_PACKETCONSTANTS_H

// Packet types
#define AGENT_INITIATION_PACKET_TYPE 0
#define METRIC_PACKET_TYPE 1
#define SERVER_INITIATION_PACKET_TYPE 2
#define ACKNOWLEDGE_PACKET_TYPE 3

// Flags
#define FLAG_ACK 0x80
#define FLAG_ERR 0x40
#define FLAG_BUSY 0x20
#define FLAG_VER 0x10
#define FLAG_RDY 0x8

#define FLAG_RESEND 0x40
#define FLAG_CLOSE_CONN 0x20

#endif //CHRONOS_PACKETCONSTANTS_H
